#!/bin/sh

java -cp sootclasses-trunk.jar soot.Main --keep-line-number --xml-attributes -f dava -pp --cp jdom.jar:jaxen-core.jar:jaxen-jdom.jar:saxpath.jar:xalan.jar:xerces.jar:xml-apis.jar --process-dir jdom.jar
