#!/bin/sh

java -cp soot-rb.jar soot.Main -pp -process-dir build/classes -cp build/classes -output-format c
java -cp soot-rb.jar soot.Main -pp -process-dir build/classes -cp build/classes -output-format J
